---
title: "Kappa Statistic"
author: "Elijah Chou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cohen's Kappa Statistic between Humans (Majority Vote) vs. System

```{r cars}
library(lpSolve)
library(irr)
item1.rater1<-c(1,1,1,1,2,1,2,1,2,1,1,2,2,2,2,2,2,2,1,1,2,2,2,2,1,1,2,2,1,1)
item1.rater2<-c(1,2,1,1,1,2,2,1,2,1,1,2,2,2,1,2,2,2,1,1,2,1,1,2,1,1,2,2,2,1)
item1<-as.matrix(cbind(item1.rater1,item1.rater2))
kappa2(item1[,c(1,2)])
kappam.fleiss(item1[,c(1,2)])
```

## Fleiss's Kappa Statistic Among 3 Human Graders

```{r pressure, echo=FALSE}
item2.rater1<-c(2,2,1,2,1,1,2,1,2,1,1,2,2,2,1,1,2,1,1,2,2,1,2,1,2,2,2,1,2,1)
item2.rater2<-c(1,1,1,1,2,1,2,2,2,2,2,1,2,2,2,2,2,2,1,1,2,2,2,2,1,1,1,2,1,1)
item2.rater3<-c(1,1,2,1,2,2,2,1,1,1,1,2,2,2,2,2,2,2,1,1,1,2,1,2,1,1,2,2,1,1)
item2<-as.matrix(cbind(item2.rater1,item2.rater2, item2.rater3))
kappam.fleiss(item2[,c(1,2,3)])
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
